### ISSUE TITLE
basic installation failed 

### ISSUE THREAD

**Issue by lironmo** [manjurulhoque/django-job-portal#39]
Hi,

create venv
pip install -r requirements.txt
python manage.py collectstatic

getting the following error:

django-job-portal>python manage.py collectstatic
Post-processing 'vendor\bootstrap\js\bootstrap.min.js' failed!

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "C:\envs\portal\lib\site-packages\django\core\management\__init__.py", line 425, in execute_from_command_line
    utility.execute()
  File "C:\envs\portal\lib\site-packages\django\core\management\__init__.py", line 419, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\envs\portal\lib\site-packages\django\core\management\base.py", line 373, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\envs\portal\lib\site-packages\django\core\management\base.py", line 417, in execute
    output = self.handle(*args, **options)
  File "C:\envs\portal\lib\site-packages\django\contrib\staticfiles\management\commands\collectstatic.py", line 187, in handle
    collected = self.collect()
  File "C:\envs\portal\lib\site-packages\django\contrib\staticfiles\management\commands\collectstatic.py", line 134, in collect
    raise processed
whitenoise.storage.MissingFileError: The file 'vendor/bootstrap/js/bootstrap.min.js.map' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage object at 0x00000223D8065CA0>.

The JS file 'vendor\bootstrap\js\bootstrap.min.js' references a file which could not be found:
  vendor/bootstrap/js/bootstrap.min.js.map

Please check the URL references in this JS file, particularly any
relative paths which might be pointing to the wrong location.

**Comment by lironmo** [comment]
workaround (3 options)- 
add missing files (all .map)
remove css comments
removing STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"  

https://stackoverflow.com/questions/26829435/collectstatic-command-fails-when-whitenoise-is-enabled

what is the proper solution? (i am new with Django framework )

**Comment by Razihmad** [comment]
I have solve you complete requirements.txt  installation issue. If you give me access I can push the code.
